export const SET_LOCATION = "SET_LOCATION";
export const SET_FILTERS = "SET_FILTERS";
export const SET_MODALS = "SET_MODALS";
export const SHOW_DELETE_STATUS = "SHOW_DELETE_STATUS";
export const SET_STATUSES = "SET_STATUSES";
export const SHOW_UPDATE_STATUS = "SHOW_UPDATE_STATUS";